POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Item three",
    "description": "This is Video three",
    "duration": 100
}

### 

// Use /videos?search= to search in title
GET http://localhost:3333/videos

###

// Use videos/id to PUT
PUT http://localhost:3333/videos/4d4e5ff9-74b1-4227-b825-f160b23e5060
Content-Type: application/json

{
    "title": "Video updated",
    "description": "This is Video updated",
    "duration": 100
}

###

// Use videos/id to DELETE
DELETE http://localhost:3333/videos/4d4e5ff9-74b1-4227-b825-f160b23e5060