POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video 01",
    "description": "This is Video 01",
    "duration": 100
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/4cdf4733-9443-43c5-ae40-6ea83693b60e
Content-Type: application/json

{
    "title": "Video 050505050",
    "description": "This is Video 05050505",
    "duration": 100
}

###

DELETE http://localhost:3333/videos/id