POST https://node-studying-thkl.onrender.com/videos
Content-Type: application/json

{
    "title": "Item five",
    "description": "This is Video five",
    "duration": 100
}

### 

// Use /videos?search= to search in title
GET https://node-studying-thkl.onrender.com/videos

###

// Use videos/id to PUT
PUT https://node-studying-thkl.onrender.com/videos/82fd3ed9-2566-4450-baef-71af048cf9c7
Content-Type: application/json

{
    "title": "Video updated",
    "description": "This is Video updated",
    "duration": 100
}

###

// Use videos/id to DELETE
DELETE https://node-studying-thkl.onrender.com/videos/336a4b02-6aba-421e-87fe-235472b7a0d2